---
title: "Week 2: Working with clients, and starting solution design"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 2 Materials

- Week 2 [Slides](https://docs.google.com/presentation/d/1WUqK8HqHlHI_ugsCmdyP3lwkk51XfiJ3I5RJivKs7vY/edit?usp=sharing)

## Week 2 Goals:

- Peer Review - 1 paragraph description - 
- Solution Design - initial schematic
- Data Exploration - a first attempt
- Communicating with clients and beyond

## Today's timeline: 

- 1:00 - 1:15 - Questions & “What worked?”
- 1:15 - 1:30 - Peer Review of Paragraph
- 1:30 - 2:30 - Solution Design
- 2:30-2:45  - Break
- 2:45 - 3:20 - Data Exploration
- 3:20 - 3:40 - Data Exploration Show and Tell (3 minutes)
- 3:40 - 3:50 - Communicating with clients 
- 3:50 - 4:00 - For next week

## What you should do before next week: 

* Add your skeleton draft sketch of your  Solution Design to [Class Working Drive Week 3 Sketches](https://drive.google.com/drive/folders/18sO6YkIUUI1IE5ysaP1xi2eXzYKAk9Y4?usp=share_link)  before next class (you can just add a screenshot if needed, )
Note: Schematics are encouraged in your D&I plan, so this could / should end up being a final figure in your submitted document. 

* Turn your sketch into a Gantt chart (Casey’s class will provide some guidance here). Add a link to [Class Working Drive Week 3 Gantt Chart Link Doc](https://docs.google.com/document/d/10SOaFWKWnNtArkVzoo2QGhC2Iw6B18nND_9R_WyHV_0/edit?usp=sharing)

* Prepare a Flash Talk on your project, be ready to present in next week’s class. Add presentation to [Class Working Drive Week 3 Flash Talks](https://drive.google.com/drive/folders/1L8pUddcgw4t12cawPE4K2NZKtnulNZjL?usp=share_link)  
