---
title: "Week 4: Faculty reviews, responding to questions, postmortems, and flash talks"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 4 Materials

-   Week 4 [Slides](https://docs.google.com/presentation/d/1Lxyi_B8uU8d2rOdobZAt8HjnsquX6VuZ0jdDBXJFmaA/edit?usp=sharing)

## Week 4 Goals:

- Check in on Capstone Design and Implementation plan 
- Formalize Problem Statement
- Making progress on Solution Design
- Feedback on data management plan
- Starting to think about testing

## Today's timeline:

- 1:00 - 1:20 - Review of Capstone Design and Implementation Plan
- 1:20 - 1:50. - Problem Statement (overview, work time)
- 1:50 - 2:45 - Design Solution Presentations and Feedback
- 2:45 - 3:00 - Break
- 3:00 - 3:15 - Pair and Share on Data Management Plan
- 3:15 - 4:00 - Testing

## What you should do before next week: 

- Draft Documentation Plan 
- Read [this short post](https://www.applause.com/blog/functional-testing-types-examples) on different types of software testing, and [this one](https://www.usgs.gov/data-management/manage-quality) on data quality, to understand some different testing and data quality flavors (we’ll discuss more next week)
- Brainstorm different ways you are concerned your product and/or data could break / fail. Prepare a 2-slide flash talk (3 minutes, 2 presenters) to share expected breaks. *This will motivate group discussions & feedback on product testing.*
