---
title: "Week 3: Data Management"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 3 Materials


## Week 3 Goals:

-   Learn about strategies for data management
-   Continue to work on solution design
-   Answer any questions on funds for your project and how to use them

## Today's timeline:

- **1:00-3:00**  Renata Curty - Data Management Plans
- **3:00-3:30**. Pair and share solution design 
- **3:30-4:00**  Bridget Mastopietro - Finanace Team Presentation



## What you should do before next week: 

-   Prepara your data management plan and be ready share. Add it (as a Google doc) to this folder on our class drive [Week4/Data Management Plan](https://drive.google.com/drive/folders/1BNT8tE4Fjsc5cfodiGaKrL2Bap29n92p?usp=sharing)  

-   Continue to work on your solution design

-   Be prepared to present you flash talk and solution design in class (you can update materials that you submitted last week if you want to incorporate updates/changes)

  -  [Class Working Drive Week 3 Gantt Chart Link Doc](https://docs.google.com/document/d/10SOaFWKWnNtArkVzoo2QGhC2Iw6B18nND_9R_WyHV_0/edit?usp=sharing)

  -  [Class Working Drive Week 3 Flash Talks](https://drive.google.com/drive/folders/1L8pUddcgw4t12cawPE4K2NZKtnulNZjL?usp=share_link)  
  
  - [Class Working Drive Week 3 Sketches](https://drive.google.com/drive/folders/18sO6YkIUUI1IE5ysaP1xi2eXzYKAk9Y4?usp=share_link) 

  
