---
title: "Week 5: Coding, Testing.. "
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 5 Materials

-   Week 5 [Slides](https://docs.google.com/presentation/d/1tfNfBAF87CYA-rbqi8fBWCeA5drOfO4xcAdZB10TlEk/edit?usp=sharing)

## Week 5 Goals:

- Gaining perspective on what makes good data science
- Practice in code testing
- Preparing for failure
- Faculty Review Logistics
- Solution design sharing

## Today's timeline:

* 1:00 - 1:45 - Announcements and Perspectives on Coding Design
* 1:45 -  2:30 - Code Design and Testing
* 2:30 -  2:45 - Test Sharing
* 2:45 - 3:00 - Break
* 3:00 - 3:10 - Failure and how to handle it
* 3:10 - 3:30 - Faculty Review Logistics
* 3:30 - 4:00 - Solution Design Peer Review

## What you should do before next week: 

- Draft Testing Plan section of Design & Implementation Plan
- Prepare a 5 minute presentation
  - Cover slide
  - Background and motivation/significance (1-2 slides
  - Problem Statement (1 slide)
  - Objective (1 slide)
  - Solution Design (2-3 slides)
  
## Resources for testing

- Jeff Perkel (2022) [How to fix your scientific coding errors](https://www.nature.com/articles/d41586-022-00217-0). Nature Technology Feature. 

- [DataONE Best Practices - Data Assurance](https://dataoneorg.github.io/Education/bp_step/assure/)

- Google [Testing and Debugging in ML](https://developers.google.com/machine-learning/testing-debugging)

- Fay et al. [Engineering Production-Grade Shiny Apps Ch. 11 - Build yourself a safety net](https://engineering-shiny.org/build-yourself-safety-net.html)

- Taschuk and Wilson (2017) [Ten simple rules for making research software more robust](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005412). PLOS Comp Bio. 
